---
- name: "Create isucon group"
  group:
    name: isucon
    gid: 1100
    state: present
    system: no

- name: "Create isucon user"
  user:
    name: isucon
    uid: 1100
    group: isucon
    password: $1$SALTsalt$e7jg2tj3sKVpmYXXmivBb0
    home: /home/isucon
    shell: /bin/bash
    state: present
    system: no

- name: "Add sudoers"
  copy:
    content: "isucon  ALL=(ALL) NOPASSWD:ALL\n"
    dest: /etc/sudoers.d/99-isucon-user
    owner: root
    group: root
    mode: 0440

- name: "Copy REVISION"
  copy:
    src: /dev/shm/files-generated/REVISION
    dest: /etc/REVISION
    owner: root
    group: root
    mode: 0644

- name: "Create /tmp/isucon11-final directory"
  file:
    path: /tmp/isucon11-final
    state: directory

- name: "Unarchive isucon11-final.tar"
  unarchive:
    src: /dev/shm/files-generated/isucon11-final.tar
    dest: /tmp/isucon11-final/
    owner: isucon
    group: isucon

- name: "Install packages"
  apt:
    name:
    - libssl-dev
    - libreadline-dev
    - gcc
    - make
    - libffi-dev
    - zlib1g-dev
    - unzip
    - pkg-config
    - autoconf
    - automake
    - build-essential
    - libxml2-dev
    - libsqlite3-dev
    - libbz2-dev
    - libkrb5-dev
    - libcurl4-openssl-dev
    - libpng-dev
    - libjpeg-dev
    - libfreetype6-dev
    - libc-client2007e-dev
    - libxslt-dev
    - libonig-dev
    - libtidy-dev
    - libzip-dev
    - default-mysql-client
    - default-libmysqlclient-dev
    update_cache: yes

- name: Install xbuild
  become: yes
  become_user: isucon
  git:
    repo: https://github.com/tagomoris/xbuild.git
    dest: /tmp/xbuild
    version: master
