backend:
  - webapp/golang/**/*
frontend:
  - webapp/frontend/**/*
benchmarker:
  - benchmarker/**/*
infrastructure:
  - provisioning/**/*
documentation:
  - docs/**/*
transplant:
  - webapp/nodejs/**/*
  - webapp/php/**/*
  - webapp/ruby/**/*
  - webapp/rust/**/*
# initial-data:
#   - extra/initial-data/**/*
#   - bench/random/**/*
