name: Nodejs

on:
  push:
    branches:
      - 'main'
    paths:
      - benchmarker/**
      - webapp/nodejs/**
      - webapp/frontend/**  # bench/assets.go の更新検知のために回す
      - dev/frontend/Dockerfile
      - dev/nodejs/Dockerfile
      - dev/nginx/default.conf
      - dev/Makefile
      - dev/compose.yaml
      - .github/workflows/nodejs.yml
  pull_request:
    paths:
      - benchmarker/**
      - webapp/nodejs/**
      - webapp/frontend/**  # bench/assets.go の更新検知のために回す
      - dev/frontend/Dockerfile
      - dev/nodejs/Dockerfile
      - dev/nginx/default.conf
      - dev/Makefile
      - dev/compose.yaml
      - .github/workflows/nodejs.yml

jobs:
  packages:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: webapp/nodejs
    steps:
      - uses: actions/checkout@v2
      - name: setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14
          check-latest: true
          cache: npm
          cache-dependency-path: ./webapp/nodejs/package-lock.json
      - name: install dependencies
        run: npm ci
  lint:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: webapp/nodejs
    needs: [packages]
    steps:
      - uses: actions/checkout@v2
      - name: setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14
          check-latest: true
          cache: npm
          cache-dependency-path: ./webapp/nodejs/package-lock.json
      - name: install dependencies
        run: npm ci
      - name: run lint
        run: npm run lint
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: setup environments
        run: TARGET=nodejs make up
        working-directory: ./dev
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: run -no-load
        run: |
          make
          ./bin/benchmarker -no-load -exit-status
        working-directory: ./benchmarker
      - name: teardown environments
        if: ${{ always() }}
        run: TARGET=nodejs make down
        working-directory: ./dev
