---
- name: "roles/contestant/tasks/main: Include nginx.yml"
  include: nginx.yml
  become_user: root

- name: "roles/contestant/tasks/main: Include mysql.yml"
  include: mysql.yml
  become_user: root

- name: "roles/contestant/tasks/main: Include isucholar.yml"
  include: isucholar.yml
  become_user: root

- name: "roles/contestant/tasks/main: Include commands.yml"
  include: commands.yml
  become_user: root
