version: '3'

services:
  frontend:
    build:
      context: ../webapp/frontend
      dockerfile: ../../dev/frontend/Dockerfile
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "8080:80"
    depends_on:
      - backend
  backend:
    build:
      context: ../webapp/ruby
      dockerfile: ../../dev/ruby/Dockerfile
    restart: always
    environment:
      MYSQL_HOSTNAME: mysql
      DEBUG: "true"
    entrypoint: dockerize -timeout 60s -wait tcp://mysql:3306 bundle exec puma -p 7000
    ports:
      - "7000:7000"
    depends_on:
      - mysql
    volumes:
      - ../webapp/data:/webapp/data:ro
      - ../webapp/sql:/webapp/sql:ro
  mysql:
    image: mysql
    restart: always
    # setup.sqlの代替
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: isucon
      MYSQL_PASSWORD: isucon
      MYSQL_DATABASE: isucholar
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
  adminer:
    image: adminer:latest
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: mysql
      ADMINER_DESIGN: nette
    ports:
      - "7001:8080"

volumes:
  mysql:
