version: '3'

services:
  backend:
    build:
      context: ..
      dockerfile: dev/${target}/Dockerfile
    restart: always
    environment:
      MYSQL_HOSTNAME: mysql
      MYSQL_DATABASE: isucholar
      MYSQL_USER: isucon
      MYSQL_PASSWORD: isucon
      MYSQL_PORT: 3306
    entrypoint: dockerize -timeout 60s -wait tcp://mysql:3306
    command: /bin/isucholar
    ports:
      - "7000:7000"
    depends_on:
      - mysql
    volumes:
      - ../webapp:/webapp

  mysql:
    image: mysql
    restart: always
    # setup.sqlの代替
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: isucon
      MYSQL_PASSWORD: isucon
      MYSQL_DATABASE: isucholar
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    expose:
      - "3306"
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql

  #TODO: prepare用のサービスを追加する
  prepare:
    build: 

volumes:
  mysql:
