---
- name: "Install Rust"
  become_user: isucon
  shell: |
    curl https://sh.rustup.rs -sSf | sh -s -- -y --no-modify-path --profile default --default-toolchain 1.55.0

- name: "Add PATH for Rust"
  become_user: isucon
  blockinfile:
    marker: "# {mark} ANSIBLE MANAGED BLOCK Rust"
    path: /home/isucon/.bashrc
    content: |
      export PATH=/home/isucon/.cargo/bin:$PATH
