---
- name: "roles/bench/tasks/bench: Deploy isucon11-final benchmarker"
  become_user: isucon
  copy:
    remote_src: yes
    src: /tmp/isucon11-final/benchmarker
    dest: /home/isucon/
    owner: isucon
    group: isucon

- name: "roles/bench/tasks/bench: Build benchmarker"
  make:
    chdir: /home/isucon/benchmarker
    target: all
