dsn: mysql://root:password@localhost:3306/isucholar
docPath: docs/schema
format:
  adjust: true
er:
  format: svg
  distance: 1
  font: M+
lint:
  requireTableComment:
    enabled: true
  requireColumnComment:
    enabled: true
    exclude:
      - id
      - created_at
      - updated_at
      - deleted_at
detectVirtualRelations:
  enabled: true

comments:
  - table: users
    tableComment: ユーザー一覧
    columnComments:
      code: 学籍番号
      name: ユーザー名
      hashed_password: 暗号化されたパスワード
      type: 学生・教員
  - table: courses
    tableComment: 科目一覧
    columnComments:
      code: 科目コード
      type: 科目種別
      name: 科目名
      description: 科目の説明
      credit: 単位数
      period: 開講時限
      day_of_week: 開講曜日
      teacher_id: 担当教員のID
      keywords: キーワード
      status: 科目ステータス
  - table: registrations
    tableComment: 履修登録一覧
    columnComments:
      course_id: 履修科目のID
      user_id: 学生のID
  - table: classes
    tableComment: 講義一覧
    columnComments:
      course_id: 科目のID
      part: 講義の順序
      title: 講義のタイトル
      description: 講義の説明
      submission_closed_at: 課題締め切り時のタイムスタンプ
  - table: submissions
    tableComment: 提出された課題一覧
    columnComments:
      user_id: 提出した学生のID
      class_id: 対象講義のID
      name: 提出したファイル名
      score: 課題のスコア
  - table: announcements
    tableComment: お知らせ一覧
    columnComments:
      course_id: 科目のID
      title: お知らせのタイトル
      message: お知らせの内容
  - table: unread_announcements
    tableComment: 未読お知らせ一覧
    columnComments:
      announcement_id: お知らせのID
      user_id: 未読の学生
      deleted_at: 既読時のタイムスタンプ
