version: '3'

services:
  nginx:
    image: nginx:1.21
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "8080:80"
    links:
      - "backend"
    depends_on:
      - frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/frontend
    ports:
      - "3000:3000"
  backend:
    build: ./golang
    restart: always
    environment:
      MYSQL_HOSTNAME: mysql
      DEBUG: "true"
    entrypoint: dockerize -timeout 60s -wait tcp://mysql:3306
    command: ./isucholar
    ports:
      - "7000:7000"
    depends_on:
      - mysql
    volumes:
      - ./sql:/sql:ro
      - ./assignments:/assignments

  mysql:
    image: mysql
    restart: always
    # setup.sqlの代替
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: isucon
      MYSQL_PASSWORD: isucon
      MYSQL_DATABASE: isucholar
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    expose:
      - "3306"
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql

  adminer:
    image: adminer:latest
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: mysql
      ADMINER_DESIGN: nette
    ports:
      - "7001:8080"

volumes:
  mysql:
