name: Build

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: isucon11-backend
  IMAGE_TAG: master

jobs:
  image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: isucon
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./webapp/golang
          push: true
          tags: ghcr.io/isucon/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
