name: CI-bench

on:
  push:
    branches:
      - 'master'
  pull_request:
    paths:
      'benchmarker/**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('./benchmarker/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - run: make
        working-directory: ./benchmarker

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          working-directory: ./benchmarker
          args: " --disable-all -E govet,staticcheck,goimports --timeout 3m0s"
