name: CI-frontend

on:
  push:
    branches:
      - 'main'
  pull_request:
    paths:
      - 'webapp/frontend/**'

defaults:
  run:
    working-directory: ./webapp/frontend

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node env
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 14
          check-latest: true
      - name: Install dependencies
        run: yarn

      - name: Run linter
        run: yarn lint

      - name: Run tests
        run: yarn test
