name: CI-webapp

on:
  push:
    branches:
      - 'main'
  pull_request:
    paths:
      - 'webapp/**'
      - '!webapp/frontend/**'

jobs:
  build:
    name: Build
    runs-on: self-hosted
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - uses: actions/checkout@v2
      - run: make
        working-directory: ./webapp/golang
  lint:
    name: Lint
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          working-directory: ./webapp/golang
          args: "-c ../../.github/.golangci.yaml"
