name: ci for go
on:
  push:
    branches: [ main ]
    paths:
      - bench/**/*
      - webapp/go/**/*
      - dev/golang/**/*
      - dev/docker-compose.yml
      - dev/Makefile
      - .github/workflows/go.yaml
  pull_request:
    paths:
      - bench/**/*
      - webapp/go/**/*
      - dev/golang/**/*
      - dev/docker-compose.yml
      - dev/Makefile
      - .github/workflows/go.yaml

jobs:
  lint:
    name: Lint
    runs-on: self-hosted
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          working-directory: ./webapp/go
          args: "-c ../../.github/.golangci.yml"
  test:
    name: Integration Test
    runs-on: self-hosted
    timeout-minutes: 15
    defaults:
      run:
        working-directory: dev
    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Install some utils
        env:
          AWS_CLI_VERSION: 2.2.16
        run: |
          curl -sL https://awscli.amazonaws.com/awscli-exe-linux-x86_64-${AWS_CLI_VERSION}.zip -o /tmp/awscliv2.zip \
            && unzip -o /tmp/awscliv2.zip -d /tmp/ \
            && /tmp/aws/install --update -i $HOME/work/_tool/isucon11-final/aws-cli -b $HOME/work/_tool/isucon11-final
      - name: Build Go App
        run: target=golang docker-compose -f docker-compose-ci.yml up -d --build -- backend mysql
      - name: Test Go App
        run: target=golang docker-compose -f docker-compose-ci.yml up --build --exit-code-from prepare -- prepare
      - name: Clean up
        if: failure() || true
        run: target=golang docker-compose -f docker-compose-ci.yml down
