name: Ruby

on:
  push:
    branches:
      - 'main'
    paths:
      - benchmarker/**
      - webapp/ruby/**
      - webapp/frontend/**  # bench/assets.go の更新検知のために回す
      - dev/frontend/Dockerfile
      - dev/ruby/Dockerfile
      - dev/nginx/default.conf
      - dev/Makefile
      - dev/compose.yaml
      - .github/workflows/ruby.yml
  pull_request:
    paths:
      - benchmarker/**
      - webapp/ruby/**
      - webapp/frontend/**  # bench/assets.go の更新検知のために回す
      - dev/frontend/Dockerfile
      - dev/ruby/Dockerfile
      - dev/nginx/default.conf
      - dev/Makefile
      - dev/compose.yaml
      - .github/workflows/ruby.yml

jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: setup environments
        run: TARGET=ruby make up
        working-directory: ./dev
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17.1
      - name: run -no-load
        run: |
          make
          ./bin/benchmarker -no-load -exit-status
        working-directory: ./benchmarker
      - name: teardown environments
        if: ${{ always() }}
        run: make down
        working-directory: ./dev
